

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1); _sage_const_63 = Integer(63); _sage_const_65 = Integer(65); _sage_const_90 = Integer(90); _sage_const_20 = Integer(20)
import random
import ast
import sys

p = random_prime(_sage_const_2 **_sage_const_64 -_sage_const_1 , False, _sage_const_2 **_sage_const_63 )
print(p)
R = Integers(p)

def gen_rand_string(n):
    return "".join([chr(random.randint(_sage_const_65 , _sage_const_90 )) for _ in range(n)])

g = mod(primitive_root(p), p)
target_str = open("flag.txt").readline()

#print(target_str)

open("target.txt","w+").write(target_str)

def send_msg(sender, recipient, content):
    print(f"{sender} {recipient} {content}")

for pos in range(len(target_str)):
    fixed_eve = gen_rand_string(_sage_const_1 )
    for iter in range(_sage_const_20 ):
        a = random.randint(_sage_const_1 , p-_sage_const_1 )
        b = random.randint(_sage_const_1 , p-_sage_const_1 )
        send_msg("Alice", "Bob", g**a)
        send_msg("Bob", "Alice", b)
        send_msg("Bob", "Alice", g**b)
        if random.randint(_sage_const_1 , _sage_const_2 ) == _sage_const_1 :
            # interception occurs
            c = random.randint(_sage_const_1 , p-_sage_const_1 )
            send_msg("Alice", "Bob", fixed_eve)
            send_msg("Alice", "Bob", g**c)
        else:
            send_msg("Alice", "Bob", target_str[pos])
            send_msg("Alice", "Bob", g**(a * b))
        print()

def input_with_timeout(prompt, timeout):
    sys.stdout.write(prompt)
    sys.stdout.flush()
    ready, _, _ = select.select([sys.stdin], [], [], timeout)
    if ready:
        return sys.stdin.readline().rstrip('\n')
    raise Exception


try:
    answer = input_with_timeout('', _sage_const_20 )
    try:
        answer = ast.literal_eval(answer)
        if target_str == answer:
            print(":o")
            print(flag)
        else:
            print("im upset")
    except Exception as e:
        print("im very upset")
except Exception as e:
    print("\nyou've let me down :(")

